/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_edma.h"
#include "stdlib.h"
#include "fsl_common.h"
#include "fsl_ctimer.h"
#include "fsl_clock.h"
#include "fsl_gpio.h"
#include "fsl_lpi2c.h"
#include "fsl_lpi2c_edma.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR (EDMA_Type *)DMA0
/* NVIC interrupt vector ID (number). */
#define INT_0_IRQN LP_FLEXCOMM2_IRQn
/* NVIC interrupt vector priority. */
#define INT_0_IRQ_PRIORITY 3
/* NVIC interrupt handler identifier. */
#define INT_0_IRQHANDLER LP_FLEXCOMM2_IRQHandler
/* NVIC interrupt vector ID (number). */
#define INT_1_IRQN EDMA_0_CH0_IRQn
/* NVIC interrupt vector priority. */
#define INT_1_IRQ_PRIORITY 3
/* NVIC interrupt handler identifier. */
#define INT_1_IRQHANDLER EDMA_0_CH0_IRQHandler
/* NVIC interrupt vector ID (number). */
#define INT_2_IRQN EDMA_0_CH1_IRQn
/* NVIC interrupt vector priority. */
#define INT_2_IRQ_PRIORITY 3
/* NVIC interrupt handler identifier. */
#define INT_2_IRQHANDLER EDMA_0_CH1_IRQHandler
/* Definition of peripheral ID */
#define CTIMER0_PERIPHERAL CTIMER0
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER0_TICK_FREQ 2343750UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER0_TICK_PERIOD 427UL
/* Definition of PWM period channel. */
#define CTIMER0_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of PWM period */
#define CTIMER0_PWM_PERIOD 2342
/* Definition of channel 1 ID */
#define CTIMER0_PWM_1_CHANNEL kCTIMER_Match_1
/* Definition of channel 1 duty */
#define CTIMER0_PWM_1_DUTY 2293
/* Definition of channel 2 ID */
#define CTIMER0_PWM_2_CHANNEL kCTIMER_Match_2
/* Definition of channel 2 duty */
#define CTIMER0_PWM_2_DUTY 2293
/* Alias for GPIO0 peripheral */
#define GPIO0_GPIO GPIO0
/* Alias for PORT0 */
#define GPIO0_PORT PORT0
/* GPIO0 interrupt vector ID (number). */
#define GPIO0_INT_0_IRQN GPIO00_IRQn
/* GPIO0 interrupt handler identifier. */
#define GPIO0_INT_0_IRQHANDLER GPIO00_IRQHandler
/* GPIO0 interrupt vector ID (number). */
#define GPIO0_INT_1_IRQN GPIO01_IRQn
/* GPIO0 interrupt handler identifier. */
#define GPIO0_INT_1_IRQHANDLER GPIO01_IRQHandler
/* BOARD_InitPeripherals defines for LP_FLEXCOMM2 */
/* Definition of peripheral ID */
#define LP_FLEXCOMM2_PERIPHERAL LPI2C2
/* Definition of peripheral base address */
#define LP_FLEXCOMM2_PERIPHERAL_BASE LPI2C2_BASE
/* Definition of the clock source frequency */
#define LP_FLEXCOMM2_CLOCK_SOURCE 12000000UL
/* LP_FLEXCOMM2 eDMA source request. */
#define LP_FLEXCOMM2_RX_DMA_REQUEST kDma0RequestMuxLpFlexcomm2Rx
/* Selected eDMA channel number. */
#define LP_FLEXCOMM2_RX_DMA_CHANNEL 0
/* Used DMA device. */
#define LP_FLEXCOMM2_RX_DMA_BASEADDR DMA0
/* LP_FLEXCOMM2 eDMA source request. */
#define LP_FLEXCOMM2_TX_DMA_REQUEST kDma0RequestMuxLpFlexcomm2Tx
/* Selected eDMA channel number. */
#define LP_FLEXCOMM2_TX_DMA_CHANNEL 1
/* Used DMA device. */
#define LP_FLEXCOMM2_TX_DMA_BASEADDR DMA0
/* Leader transfer buffer size */
#define LP_FLEXCOMM2_MASTER_BUFFER_SIZE 10
/* Definition of peripheral ID */
#define CTIMER4_PERIPHERAL CTIMER4
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER4_TICK_FREQ 1171875UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER4_TICK_PERIOD 853UL
/* Definition of PWM period channel. */
#define CTIMER4_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of PWM period */
#define CTIMER4_PWM_PERIOD 1170
/* Definition of peripheral ID */
#define CTIMER2_PERIPHERAL CTIMER2
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER2_TICK_FREQ 150000000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER2_TICK_PERIOD 7UL
/* Definition of PWM period channel. */
#define CTIMER2_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of PWM period */
#define CTIMER2_PWM_PERIOD 2999999
/* Definition of channel 2 ID */
#define CTIMER2_PWM_0_CHANNEL kCTIMER_Match_2
/* Definition of channel 2 duty */
#define CTIMER2_PWM_0_DUTY 2775000

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern edma_config_t DMA0_config;
extern const ctimer_config_t CTIMER0_config;
extern const lpi2c_master_config_t LP_FLEXCOMM2_masterConfig;
extern edma_handle_t LP_FLEXCOMM2_RX_Handle;
extern edma_handle_t LP_FLEXCOMM2_TX_Handle;
extern lpi2c_master_edma_handle_t LP_FLEXCOMM2_master_handle;
extern uint8_t LP_FLEXCOMM2_master_buffer[LP_FLEXCOMM2_MASTER_BUFFER_SIZE];
extern lpi2c_master_transfer_t LP_FLEXCOMM2_masterTransfer;
extern const ctimer_config_t CTIMER4_config;
extern const ctimer_config_t CTIMER2_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
